version: '3.6'

networks:
  gateway:
    external: true
    name: "gateway"

services:
  web:
    image: gitlab/gitlab-ce:$VERSION
    container_name: gitlab
    hostname: "${HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL}'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "${SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_pool'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - "gateway"
    restart: "unless-stopped"

  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
      - '/cache'
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.accept_source_route=1
    networks:
      - "gateway"
    restart: "unless-stopped"
